INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (1,'7777777','11.11.1111','elephant','bobo');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (2,'6666666','22.11.2222','T-Rex','Franklin');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (3,'5555555','02.12.1992','unicorn','Ponny');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (4,'4444444','13.7.1563','doublecorn','Henry');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (5,'3333333','11.11.1111','triplecorn','Ponny');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (6,'2222222','02.12.1992','rat','Ellis');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (7,'1111111','18.05.1546','rat','Johnny');
INSERT INTO APP.ANIMAL (ANIMAL_ID, ANIMAL_CHIP, ANIMAL_BIRTH, ANIMAL_SPECIE, ANIMAL_NAME) VALUES (8,'0000000','18.10.1939','T-Rex','T-Harvey Oswald');

INSERT INTO APP.STAFF (STAFF_ID, STAFF_PERSONAL_ID, STAFF_NAME, STAFF_LASTNAME, STAFF_BIRTH,STAFF_CONTACT) VALUES (1,'1111111','Bob','Bobinski','11.11.1111','bob@mail.com');
INSERT INTO APP.STAFF (STAFF_ID, STAFF_PERSONAL_ID, STAFF_NAME, STAFF_LASTNAME, STAFF_BIRTH,STAFF_CONTACT) VALUES (2,'2222222','Jane','NotBobinski','22.11.2222','jane@mail.com');
INSERT INTO APP.STAFF (STAFF_ID, STAFF_PERSONAL_ID, STAFF_NAME, STAFF_LASTNAME, STAFF_BIRTH,STAFF_CONTACT) VALUES (4,'3333333','Alfred','AlsoNotBobinski','11.11.1111','alfie@mail.com');
INSERT INTO APP.STAFF (STAFF_ID, STAFF_PERSONAL_ID, STAFF_NAME, STAFF_LASTNAME, STAFF_BIRTH,STAFF_CONTACT) VALUES (5,'4444444','Frederic','AlsoNotBobinski','22.11.2222','freddie@mail.com');
INSERT INTO APP.STAFF (STAFF_ID, STAFF_PERSONAL_ID, STAFF_NAME, STAFF_LASTNAME, STAFF_BIRTH,STAFF_CONTACT) VALUES (6,'5555555','Bob','ButNotBobinski','22.11.2222','bob@mail.com');

INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (1,'wheat',1500,600);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (2,'bread',3000,600);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (3,'cheese',1500,400);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (4,'hay',10000,2000);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (5,'popcorn',1500,600);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (6,'wheat',7000,2500);
INSERT INTO APP.FEED (FEED_ID, FEED_NAME, FEED_AMOUNT, FEED_MINIMUM) VALUES (7,'carrot',153,2000);